BEGIN TRANSACTION;
ALTER TABLE "exam" ADD "dv219f" INTEGER DEFAULT(0);
ALTER TABLE "exam" ADD "dv219s" INTEGER DEFAULT(0);
ALTER TABLE "exam" ADD "dv336f" INTEGER DEFAULT(0);
ALTER TABLE "exam" ADD "dv336s" INTEGER DEFAULT(0);
UPDATE "settings" SET "value" = '6' WHERE "name" = 'VerDB';
COMMIT;
